// This file was automatically generated by lister-gen

package v1alpha1

// TemplateRouterListerExpansion allows custom methods to be added to
// TemplateRouterLister.
type TemplateRouterListerExpansion interface{}

// TemplateRouterNamespaceListerExpansion allows custom methods to be added to
// TemplateRouterNamespaceLister.
type TemplateRouterNamespaceListerExpansion interface{}
